"""
Django settings for wealthpro project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w_anj&11r^lm5@sltv*t6q(&im7kch!uj*p4*v-0xd5j^61csc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'wealthpro-c4ghhwhkh6evbwdu.centralus-01.azurewebsites.net', 'nextgenerationwealthpro.com', 'www.nextgenerationwealthpro.com', '13.59.63.39']
# Accept some malformed requests
SECURE_PROXY_SSL_HEADER = None
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main.apps.MainConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wealthpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'wealthpro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_ROOT = BASE_DIR / 'productionfiles'
STATIC_URL = 'static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings
# AWS SES configuration
AWS_REGION = 'us-east-2'  # US East (Ohio) region
USE_SES = True  # Set to False to disable SES and use SMTP only

# Custom backend that chooses between SES and SMTP
EMAIL_BACKEND = 'main.email_backend.SESEmailBackend'

# AWS SES settings - values should be provided by AWS IAM
EMAIL_HOST = 'email-smtp.us-east-2.amazonaws.com'  # SES SMTP endpoint
EMAIL_PORT = 587                                   # Port for TLS
EMAIL_USE_TLS = True                              # Use TLS for security
EMAIL_HOST_USER = ''                              # SES SMTP username (to be filled)
EMAIL_HOST_PASSWORD = ''                          # SES SMTP password (to be filled)
DEFAULT_FROM_EMAIL = 'info@nextgenerationwealthpro.com'  # Verified sender email
CONTACT_EMAIL = 'krishna.dhakal03@gmail.com'      # Where contact form emails go

# Fallback to regular SMTP if SES is disabled or credentials are not available
if not USE_SES or not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD:
    # Fallback email settings
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'                 # Gmail SMTP server
    EMAIL_PORT = 587                              # Port for TLS
    EMAIL_USE_TLS = True                          # Use TLS for security
    EMAIL_HOST_USER = 'krishna.dhakal03@gmail.com'  # Your Gmail email address
    EMAIL_HOST_PASSWORD = 'swjf ceoe adxv engz'   # Your Gmail App Password
    DEFAULT_FROM_EMAIL = 'krishna.dhakal03@gmail.com'

# Media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Security settings - enabled in production only
if not DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_CONTENT_TYPE_NOSNIFF = True

# Trusted origins for CSRF
CSRF_TRUSTED_ORIGINS = [
    'https://nextgenerationwealthpro.com',
    'https://www.nextgenerationwealthpro.com',
    'https://wealthpro-c4ghhwhkh6evbwdu.centralus-01.azurewebsites.net',
    'http://13.59.63.39',
    'https://13.59.63.39',
]

# Add any custom domains or EC2 instances here
if 'CSRF_TRUSTED_ORIGINS' in os.environ:
    CSRF_TRUSTED_ORIGINS += env.list('CSRF_TRUSTED_ORIGINS')

# Caching Configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-wealthpro-cache',
        'TIMEOUT': 3600,  # 1 hour default timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000  # Maximum number of entries in cache
        }
    }
}

# Cache middleware settings
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 600  # 10 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'wealthpro'

# Optimize database connections
DATABASES['default']['CONN_MAX_AGE'] = 600  # Keep connections alive for 10 minutes

