# Generated by Django 5.1.4 on 2025-01-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
