# Generated by Django 5.1.4 on 2025-01-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeInfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=1000)),
                ('imgUrl', models.CharField(max_length=500)),
                ('imgAltText', models.CharField(max_length=500)),
                ('imgClass', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sliderImageUrl', models.CharField(max_length=500)),
                ('sliderImageAltText', models.CharField(max_length=500)),
            ],
        ),
    ]
