# Generated by Django 5.1.4 on 2025-01-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_homeinfosection_homesliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebookUrl', models.CharField(max_length=500)),
                ('youtubeUrl', models.CharField(max_length=500)),
                ('linkedinUrl', models.CharField(max_length=500)),
                ('instagramUrl', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=1000)),
                ('imgUrl', models.CharField(max_length=500)),
                ('imgAltText', models.CharField(max_length=500)),
                ('imgClass', models.CharField(max_length=500)),
                ('serviceUrl', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('websiteUrl', models.CharField(max_length=500)),
                ('agentNo', models.CharField(max_length=100)),
            ],
        ),
    ]
