# Generated by Django 5.1.4 on 2025-01-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_footersection_servicessection_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='profileUrl',
            field=models.CharField(default='images/', max_length=500),
        ),
    ]
