# Generated by Django 5.1.4 on 2025-01-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_team_profileurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfosection',
            name='imgUrl',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='homesliderimage',
            name='sliderImageUrl',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='servicessection',
            name='imgUrl',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
