# Generated by Django 5.1.4 on 2025-03-23 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_zoomavailableslot_zoomcredentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text="Font Awesome icon class, e.g., 'fa-heart' for health", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceBaseRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('ANY', 'Any')], default='ANY', max_length=10)),
                ('base_monthly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_thousand', models.DecimalField(decimal_places=2, help_text='Additional rate per $1,000 of coverage', max_digits=10)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_rates', to='main.insurancetype')),
            ],
            options={
                'unique_together': {('insurance_type', 'min_age', 'max_age', 'gender')},
            },
        ),
    ]
