# Generated by Django 5.1.4 on 2025-03-23 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_insurancetype_insurancebaserate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInvestmentReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_years', models.IntegerField(help_text='Policy term in years (e.g., 10, 15, 20)')),
                ('annual_return_rate', models.DecimalField(decimal_places=2, help_text='Annual return rate percentage (e.g., 5.25 for 5.25%)', max_digits=5)),
                ('guaranteed_return', models.BooleanField(default=False, help_text='Whether the return rate is guaranteed or estimated')),
                ('tax_benefits', models.BooleanField(default=True, help_text='If the policy provides tax benefits')),
                ('maturity_bonus_percent', models.DecimalField(decimal_places=2, default=0, help_text='Additional bonus percentage at maturity', max_digits=5)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_returns', to='main.insurancetype')),
            ],
            options={
                'unique_together': {('insurance_type', 'term_years')},
            },
        ),
    ]
