# Generated by Django 5.1.4 on 2025-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_staterateadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Next Generation Wealth Pro', max_length=200)),
                ('site_tagline', models.CharField(default='Wealth Management', max_length=200)),
                ('address', models.CharField(default='123 Street, New York, USA', max_length=200)),
                ('phone', models.CharField(default='+012 345 67890', max_length=20)),
                ('email', models.EmailField(default='info@nextgenwealthpro.com', max_length=254)),
                ('about_us_short', models.TextField(default='Next Generation Wealth Pro provides comprehensive wealth management services.')),
                ('about_us_full', models.TextField(blank=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('footer_text', models.TextField(blank=True)),
                ('cache_timeout', models.PositiveIntegerField(default=3600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
