# Generated by Django 5.1.4 on 2025-03-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_saturday',
            field=models.CharField(default='By appointment', help_text='Business hours for Saturday', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_sunday',
            field=models.CharField(default='Closed', help_text='Business hours for Sunday', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='business_hours_weekdays',
            field=models.CharField(default='9:00 AM - 5:00 PM', help_text='Business hours for weekdays', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@nextgenwealthpro.com', help_text='Email address to receive contact form submissions', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='default_from_email',
            field=models.EmailField(default='info@nextgenwealthpro.com', help_text='Default sender email address', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP server port'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS for secure email transmission'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_csrf_protection',
            field=models.BooleanField(default=True, help_text='Enable CSRF protection in production'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_secure_cookies',
            field=models.BooleanField(default=True, help_text='Enable secure cookies in production'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='enable_ssl_redirect',
            field=models.BooleanField(default=True, help_text='Enable SSL redirect in production'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_embed_url',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3022.9663095343016!2d-74.00425882426698!3d40.71116937132799!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c25a23e28c1191%3A0x49f75d3281df052a!2s150%20Park%20Row%2C%20New%20York%2C%20NY%2010007%2C%20USA!5e0!3m2!1sen!2sbg!4v1685637930992!5m2!1sen!2sbg', help_text='Google Maps embed URL for contact page'),
        ),
    ]
