# Generated by Django 5.1.4 on 2025-03-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_sitesettings_business_hours_saturday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='aws_region',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('af-south-1', 'Africa (Cape Town)'), ('ap-east-1', 'Asia Pacific (Hong Kong)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-3', 'Asia Pacific (Osaka)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ca-central-1', 'Canada (Central)'), ('eu-central-1', 'Europe (Frankfurt)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)'), ('eu-south-1', 'Europe (Milan)'), ('eu-west-3', 'Europe (Paris)'), ('eu-north-1', 'Europe (Stockholm)'), ('me-south-1', 'Middle East (Bahrain)'), ('sa-east-1', 'South America (São Paulo)')], default='us-east-1', help_text='AWS region for Amazon SES (if using SES)', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_password',
            field=models.CharField(default='', help_text='SMTP password or IAM SMTP password for Amazon SES', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host_user',
            field=models.CharField(default='', help_text='SMTP username or IAM SMTP user for Amazon SES', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_provider',
            field=models.CharField(choices=[('smtp', 'Standard SMTP'), ('ses', 'Amazon SES'), ('mailgun', 'Mailgun'), ('sendgrid', 'SendGrid')], default='smtp', help_text='Email service provider', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text="Use SSL instead of TLS (don't enable both)"),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='contact@nextgenwealthpro.com', help_text='Email address to receive contact form submissions (must be verified)', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='default_from_email',
            field=models.EmailField(default='info@nextgenwealthpro.com', help_text='Default sender email address (must be verified in Amazon SES)', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(default='smtp.gmail.com', help_text='SMTP server hostname (e.g., email-smtp.us-east-1.amazonaws.com for Amazon SES)', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP server port (587 for TLS, 465 for SSL)'),
        ),
    ]
