# Generated by Django 5.1.7 on 2025-04-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_sitesettings_aws_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceinvestmentreturn',
            name='aggressive_return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aggressive scenario return rate', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinvestmentreturn',
            name='conservative_return_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Conservative scenario return rate', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='insuranceinvestmentreturn',
            name='historical_performance',
            field=models.TextField(blank=True, help_text='Description of historical performance'),
        ),
        migrations.CreateModel(
            name='CSOMortalityTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(help_text='Age of the insured')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=5)),
                ('smoker_status', models.CharField(choices=[('NS', 'Non-smoker'), ('SM', 'Smoker'), ('ANY', 'Any')], default='ANY', max_length=5)),
                ('mortality_rate', models.DecimalField(decimal_places=6, help_text='Annual mortality rate per 1,000 individuals', max_digits=10)),
                ('table_version', models.CharField(default='2017 CSO', help_text='Version of the CSO table', max_length=10)),
            ],
            options={
                'verbose_name': 'CSO Mortality Table Entry',
                'verbose_name_plural': 'CSO Mortality Table Entries',
                'unique_together': {('age', 'gender', 'smoker_status', 'table_version')},
            },
        ),
        migrations.CreateModel(
            name='DisclaimerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_updated', models.DateField(auto_now=True)),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disclaimers', to='main.insurancetype')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the risk factor', max_length=100)),
                ('factor_type', models.CharField(choices=[('LIFE', 'Life Insurance'), ('HEALTH', 'Health Insurance'), ('AUTO', 'Auto Insurance'), ('HOME', 'Home Insurance')], max_length=10)),
                ('description', models.TextField(help_text='Description of how this factor affects premiums')),
            ],
            options={
                'unique_together': {('name', 'factor_type')},
            },
        ),
        migrations.CreateModel(
            name='RiskFactorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(help_text="The condition or value (e.g., 'Smoker', 'High Blood Pressure')", max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=3, help_text='Multiplier applied to base premium (e.g., 1.5 for 50% increase)', max_digits=5)),
                ('risk_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='main.insuranceriskfactor')),
            ],
        ),
        migrations.CreateModel(
            name='StateRegulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], max_length=2)),
                ('min_coverage_required', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum coverage amount required by state law', max_digits=12, null=True)),
                ('special_requirements', models.TextField(blank=True, help_text='Special requirements or disclosures for this state')),
                ('filing_requirements', models.TextField(blank=True, help_text='Filing requirements for this insurance type in this state')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_regulations', to='main.insurancetype')),
            ],
            options={
                'unique_together': {('state', 'insurance_type')},
            },
        ),
    ]
