# Generated by Django 5.1.4 on 2026-05-09 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_insuranceinvestmentreturn_aggressive_return_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme_accent_color',
            field=models.CharField(default='#3B82F6', help_text='Accent color controls highlights, hover states, and links. Use #RGB or #RRGGBB.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_mode',
            field=models.CharField(choices=[('default_blue', 'Default Blue'), ('premium_dark', 'Premium Dark'), ('trust_navy', 'Trust Navy'), ('modern_teal', 'Modern Teal'), ('executive_gold', 'Executive Gold'), ('custom', 'Custom')], default='premium_dark', help_text='Choose a preset or Custom for admin-managed site branding colors.', max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_previous_palette_json',
            field=models.JSONField(blank=True, help_text='Previous palette values are saved before theme changes for manual rollback.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_previous_palette_saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_primary_color',
            field=models.CharField(default='#02070F', help_text='Primary color controls the main brand, navigation, and button tone. Use #RGB or #RRGGBB.', max_length=7),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='theme_use_smart_palette',
            field=models.BooleanField(default=True, help_text='Smart palette keeps contrast and readability safe across navigation, buttons, footer, and links.'),
        ),
    ]
