# Generated by Django 5.1.4 on 2026-05-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_sitesettings_theme_accent_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteColorBranding',
            fields=[
            ],
            options={
                'verbose_name': 'Site Color / Branding',
                'verbose_name_plural': 'Site Color / Branding',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.sitesettings',),
        ),
    ]
