# Generated by Django 5.1.4 on 2026-05-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_sitecolorbranding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='theme_mode',
            field=models.CharField(choices=[('default_blue', 'Default Blue'), ('premium_dark', 'Premium Dark'), ('trust_navy', 'Trust Navy'), ('modern_teal', 'Modern Teal'), ('executive_gold', 'Executive Gold'), ('clean_blue', 'Clean Blue'), ('carrier_classic', 'Carrier Classic'), ('custom', 'Custom')], default='premium_dark', help_text='Choose a preset or Custom for admin-managed site branding colors.', max_length=30),
        ),
    ]
