# Generated by Django 5.2.5 on 2026-05-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_sitesettings_theme_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disclaimer_scroll_enabled',
            field=models.BooleanField(default=True, help_text='Enable horizontal scrolling animation for disclaimer text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='disclaimer_text',
            field=models.TextField(default='This site is for educational purposes only.', help_text='Text to display in the disclaimer bar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_disclaimer_bar',
            field=models.BooleanField(default=True, help_text='Show scrolling disclaimer bar below navbar'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_insurance_calculator_menu',
            field=models.BooleanField(default=True, help_text='Show Insurance Calculator menu item in navigation'),
        ),
    ]
