# Generated by Django 5.2.5 on 2026-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_sitesettings_disclaimer_scroll_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='disclaimer_scroll_speed_seconds',
            field=models.PositiveIntegerField(default=20, help_text='Scrolling speed in seconds. Lower = faster, higher = slower. Recommended: 15-35.'),
        ),
    ]
